### ISSUE TITLE
Installing Data Mover Service in Container failed

### ISSUE THREAD

**Issue by JabiDev** [VeeamHub/veeam-docker#8]
Hi,

After Setting up the Docker Env., once i'll add the securerepo as Linux host, it tells me:
Error    Installing Veeam Data Mover service Error: Failed to invoke command /opt/veeam/transport/veeamtransport --install 6162: Initialization system is not supported
                              
                             Failed to invoke command /opt/veeam/transport/veeamtransport --install 6162: Initialization system is not supported
It finishes with a warning ...
But once i add the Backup Repository and Check "Make recent backups immutable for X days, it says:
Unable to set the immutability option cannot find transport service on host
If i hit continue .. it prompts me to the Linux Server Setup ...
this time it says that the Veeam Data Mover Service is exisiting but then it throws a new error:

Error    Resolving server certificate thumbprint Error: Failed to invoke command /opt/veeam/transport/veeamtransport --get-fingerprint: Failed to get server fingerprint: there is no certificate.
                              
                             Failed to invoke command /opt/veeam/transport/veeamtransport --get-fingerprint: Failed to get server fingerprint: there is no certificate.

If i uncheck the immutability option the repo works, but not with immutablity ?

anyone else had this problem ?

**Comment by JabiDev** [comment]
also: 
if i bash into the docker container and run the following:
`/opt/veeam/transport/veeamtransport --get-fingerprint`

it says:
Failed to get server fingerprint: there is no certificate.


is there any way to gernerate the certs ?

**Comment by tsightler** [comment]
This project was build for Veeam Backup and Replication v10 prior to the existence of native immutable repository support that was introduced in v11.  It is not compatible with the immutable repository approach used by v11 due to the fact that this new approach requires persistent services that run elevated and needs an init system which this container does not include.

While it's still possible to use the Docker based repository with v11 using the traditional non-persistent data mover method, it's highly recommended to use the v11 native immutable support instead.
